name: Release Go Binary

on:
  push:
    tags:
      - 'v*.*.*'  # e.g. v0.1.0

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest

    permissions:
      contents: write  # to upload release assets
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build binaries
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/mcphetzner-linux-amd64
          GOOS=darwin GOARCH=amd64 go build -o dist/mcphetzner-darwin-amd64
          GOOS=windows GOARCH=amd64 go build -o dist/mcphetzner-windows-amd64.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
